### ISSUE TITLE
[Feature request] Highlight the legend section for the selected hour

### ISSUE THREAD

**Issue by cestevezdev** [marcusolsson/grafana-hourly-heatmap-panel#15]
This is a suggestion for improving the readability of the control.
In the current version (0.6.0), the mouse hover on a specific hour provides a tooltip with a pretty good summary for that interval:
![image](https://user-images.githubusercontent.com/16516648/95781888-fa799380-0cce-11eb-9ca5-58012fbbc6d2.png)

I wonder if apart from visualizing that tooltip, it would be possible to highlight the legend area for that specific hour. When you have a gradient of similar colors, it is not easy to distinguish the applicable interval (without reading the actual numbers... that takes "more" time):
![image](https://user-images.githubusercontent.com/16516648/95782294-df5b5380-0ccf-11eb-8363-893b1dea31f1.png)
A thin line rounding the applicable box in the legend would be enough. But could be nice other options like a circle in the applicable box:
![image](https://user-images.githubusercontent.com/16516648/95782532-4f69d980-0cd0-11eb-8544-c061a0ff7a87.png)

**Comment by marcusolsson** [comment]
I love the idea! Makes total sense for the plugin to be able to show something like that. 

The reason why the legend is so low resolution is for performance reasons. The legend currently draws a SVG element for each step along the legend, i.e. higher resolution = more elements = worse performance. It's something I'd like to fix so that we have a nice gradient without the performance hit. In other words, the highlighted region shouldn't depend on the step size.

We could still have a rectangular window of fixed size. Another option would be to have a triangle above or below the legend that points at the current value.

I don't know when I'll have the time to work on this unfortunately. Hopefully within a month.

**Comment by cestevezdev** [comment]
Thanks for the quick response! (and sorry for my late response :-( )
Definitively that makes sense.
A triangle could do the job:
![image](https://user-images.githubusercontent.com/16516648/99889590-f0946a00-2c56-11eb-8c9b-191b8609f18c.png)

Maybe one of the handicaps could be to select the appropriate color for the triangle, so It could be clearly visible in all gradient positions.

**Comment by marcusolsson** [comment]
Fixed in 5efcf8cec649c1875f7dd041b71f7194db65ae48.

You can enable it under **Legend** -> **Show value indicator** (it's disabled by default).

<img width="1031" alt="Screen Shot 2020-12-06 at 20 47 56" src="https://user-images.githubusercontent.com/8396880/101290706-54489680-3804-11eb-8460-4a5108a83010.png">

**Comment by marcusolsson** [comment]
Available in [v0.9.0](https://grafana.com/grafana/plugins/marcusolsson-hourly-heatmap-panel?version=0.9.0) 🎉

**Comment by cestevezdev** [comment]
Wonderful! Thanks for the enhancement!
![image](https://user-images.githubusercontent.com/16516648/108824022-82e33b80-75c1-11eb-95fa-890d854c22b0.png)
