### ISSUE TITLE
When I use sum calculation, the value is wrong

### ISSUE THREAD

**Issue by chouqimin** [marcusolsson/grafana-hourly-heatmap-panel#18]
As title,when I use the sum calculation
The value of 12/21 00:00~01:00 is 474000 (100000 + 150000 + 24000 + 200000)
But the chart only shows 200000, I guess that value is the last one

![image](https://user-images.githubusercontent.com/36119806/103198300-f26ede80-4922-11eb-914a-daf085933933.png)

When I use the count calculation, I have the same problem, it only returns 1 data.
The correct answer is 4 times

**Comment by marcusolsson** [comment]
Thanks for reporting. This is a [known bug](https://github.com/marcusolsson/grafana-hourly-heatmap-panel/issues/16). The max and min uses the extents of the fields rather than the aggregation. If you know (approximately) the min and max of the aggregation, you can set it yourself under Field options.
