### ISSUE TITLE
Plugin fails to load if not logged in

### ISSUE THREAD

**Issue by quaintdev** [marcusolsson/grafana-hourly-heatmap-panel#21]
First of all nice work on this plugin. It's exactly what I was looking for.

Coming to issue, I am trying to share my dashboard with others but this plugin keeps giving Error loading: marcusolsson-hourly-heatmap-panel. Rest of the visualizations load without any issue. Moreover if I login the plugin does not show any issue. 

Note that the issue occurs only with anonymous users.

Any suggestions regarding this? Thanks in advance.

**Comment by marcusolsson** [comment]
Interesting. Never heard about this before. I'll try to look into this this week. Thanks for letting me know!

**Comment by marcusolsson** [comment]
I got around to investigate this. Unfortunately, I'm not able to reproduce this. Could you share some details on what version of the plugin and Grafana you're currently running?

Also what permissions do anonymous users have?

**Comment by quaintdev** [comment]
Grafana: 7.4.0
Plugin: 0.9.1

I just noticed that both have updates. I will update and report back. Regarding anonymous user, I have below config in grafana.ini
```
[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Viewer
hide_version = true
```

**Comment by quaintdev** [comment]
The issue still exists. If I open my dashboard in incognito it looks like below

![image](https://user-images.githubusercontent.com/59229571/110141237-f7587e80-7dfa-11eb-8fc8-566e524d1493.png)

If I am logged in then it works as expected.

**Comment by marcusolsson** [comment]
So the problem is apparently with `hide_version`. The plugin tries to access the Grafana version to determine what features are available. If `hide_version` is set to `true`, not even the plugin can access the version. 

I'm not actually sure about how we should go about fixing this. If the plugin don't know what features it can safely use, it needs to guess. Either we return `true` for all capabilities, or `false` for all capabilities. Either way, the plugin may crash if a capability is missing or is required.
